"""Added Employee table

Revision ID: 9fc247431831
Revises: 9c7b5c3166bf
Create Date: 2022-01-26 09:49:09.258718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc247431831'
down_revision = '9c7b5c3166bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=150), nullable=False),
    sa.Column('Password', sa.String(length=150), nullable=False),
    sa.Column('Role', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Employee')
    # ### end Alembic commands ###
